# PROYECTO DE PRÁCTICAS 3 - GESTIÓN DE CLASES
# GRUPO C
# CREACIÓN DE BD, TABLAS, CONSULTAS

-- Creo la Base de datos `ppr3_v2`
CREATE DATABASE IF NOT EXISTS ppr3_v2;
USE ppr3_v2;

---------------------
# PARA BORRAR LA BASE DE DATOS
DROP DATABASE ppr3_v2;
---------------------


CREATE TABLE IF NOT EXISTS CARRERAS(
    ID INT NOT NULL,
    TITULO_ABREVIADO VARCHAR(10) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MATERIAS (
    CODIGO INT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,  
    ID_CARRERA INT NOT NULL,
    PRIMARY KEY (CODIGO),
    CONSTRAINT FK_MATERIAS_ID_CARRERA FOREIGN KEY (ID_CARRERA) REFERENCES CARRERAS(ID)
);

CREATE TABLE IF NOT EXISTS PERSONA (
    DNI INT(8) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20)  NOT NULL,
    CARGO VARCHAR(30) NOT NULL,
    PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS USUARIO(
    CODIGO INT NOT NULL,
    DNI INT(8) NOT NULL,
    MAIL VARCHAR(50) NOT NULL,
    CONTRASEÑA VARCHAR(40) NOT NULL,
    PRIMARY KEY (CODIGO),
    CONSTRAINT FK_USUARIO_DNI FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
    CONSTRAINT UK_USUARIO_DNI UNIQUE(DNI)
);

CREATE TABLE IF NOT EXISTS CLASES(
    ID_CLASE INT NOT NULL AUTO_INCREMENT,
    CODIGO_USUARIO INT NOT NULL ,
    CODIGO_MATERIA INT NOT NULL,
    COMISION VARCHAR(10) NOT NULL,
    FECHA DATE NOT NULL,
    HORA VARCHAR(13) NOT NULL,
    TEMAS VARCHAR(50),
    NOVEDADES VARCHAR(50),
    AULA INT ,
    ARCHIVOS VARCHAR(500),
    PRIMARY KEY (ID_CLASE,CODIGO_USUARIO,CODIGO_MATERIA),
    CONSTRAINT FK_CLASES_CODIGO_USUARIO FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_CLASES_CODIGO_MATERIA FOREIGN KEY (CODIGO_MATERIA) REFERENCES MATERIAS(CODIGO),
    CONSTRAINT CK_CLASES_COMISION CHECK (COMISION="1.º, 1.ª" OR COMISION="1.º, 2.ª" OR COMISION="1.º, 3.ª"),
    CONSTRAINT CK_CLASES_HORA CHECK (HORA="8:00-10:00" OR HORA="10:10-12:00" OR HORA="8:00-12:00" OR HORA="18:00-20:00" OR HORA="20:10-22:00" OR HORA="18:00-22:00")
);

CREATE TABLE IF NOT EXISTS ROLES(
    CODIGO INT NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS MODULOS(
    CODIGO INT NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS ROLXMOD(
    CODIGO_ROL INT NOT NULL,
    CODIGO_MODULO INT NOT NULL,
    PRIMARY KEY (CODIGO_ROL,CODIGO_MODULO),
    CONSTRAINT FK_ROLXMOD_CODIGO_ROL FOREIGN KEY(CODIGO_ROL) REFERENCES ROLES (CODIGO),
    CONSTRAINT FK_ROLXMOD_CODIGO_MODULO FOREIGN KEY(CODIGO_MODULO) REFERENCES MODULOS (CODIGO)
);

CREATE TABLE IF NOT EXISTS USUXROL(
    CODIGO_USUARIO INT NOT NULL,
    CODIGO_ROL INT NOT NULL,
    PRIMARY KEY (CODIGO_USUARIO,CODIGO_ROL),
    CONSTRAINT FK_USUXROL_CODIGO_USUARIO FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_USUXROL_CODIGO_ROL FOREIGN KEY (CODIGO_ROL) REFERENCES ROLES(CODIGO)
);



# INSERTAR datos

-- Insertado datos en la tabla CARRERAS
INSERT INTO carreras
VALUES (1,"TSAS","Tecnicatura Superior en Analista de Sistemas");

-- Insertado datos en la tabla MATERIAS
INSERT INTO MATERIAS
VALUES (1,"Análisis Matemático 1",1),
(2,"Inglés 2",1),
(3,"Prácticas Profesionalizantes 3",1);

-- Insertado datos en la tabla PERSONA
INSERT INTO PERSONA
VALUES (34567892,"Jose","Perez","Supremo");

-- Insertado datos en la tabla USUARIO
INSERT INTO USUARIO 
VALUES (1,34567892,"34567892@itbeltran.com","ola");

-- Insertado datos en la tabla ROLES
INSERT INTO ROLES VALUES (1,"DSFDS");

-- Insertado datos en la tabla MODULOS
INSERT INTO MODULOS VALUES (1,"UNA DESCRIPCION");

-- Insertado datos en la tabla ROLXMOD
INSERT INTO ROLXMOD VALUES (1,1);

-- Insertado datos en la tabla USUXMOD
INSERT INTO USUXROL VALUES (1,1);



# TRUNCAR TABLAS
TRUNCATE TABLE CLASES
TRUNCATE TABLE MATERIAS
TRUNCATE TABLE CARRERAS
TRUNCATE TABLE USUXROL
TRUNCATE TABLE ROLXMOD
TRUNCATE TABLE USUARIO
TRUNCATE TABLE PERSONA 
TRUNCATE TABLE ROLES
TRUNCATE TABLE MODULOS

# DROPEAR TABLAS
DROP TABLE CLASES
DROP TABLE MATERIAS
DROP TABLE CARRERAS
DROP TABLE USUXROL
DROP TABLE ROLXMOD
DROP TABLE USUARIO
DROP TABLE PERSONA 
DROP TABLE ROLES
DROP TABLE MODULOS